# Generated by Django 5.1.6 on 2025-04-20 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothing',
            name='price_per_day',
        ),
        migrations.AddField(
            model_name='clothing',
            name='price_per_day_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='clothing',
            name='price_per_day_3',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='clothing',
            name='price_per_day_5',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='clothing',
            name='price_per_day_7',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
