# Generated by Django 5.1.6 on 2025-04-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0002_remove_clothing_price_per_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='color',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
