# Generated by Django 5.1.6 on 2025-04-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0003_clothing_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='color',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
