# Generated by Django 5.1.6 on 2025-04-20 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0005_alter_clothing_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='care_instructions',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='clothing',
            name='design',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='clothing',
            name='fit',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='clothing',
            name='material',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='clothing',
            name='perfect_for',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='clothing',
            name='sizes_available',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='clothing',
            name='versatility',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
