# Generated by Django 5.1.6 on 2025-04-20 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0006_clothing_care_instructions_clothing_design_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothing',
            old_name='description',
            new_name='product_Details',
        ),
    ]
