# Generated by Django 5.1.6 on 2025-04-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0007_rename_description_clothing_product_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothing',
            old_name='product_Details',
            new_name='product_details',
        ),
        migrations.AlterField(
            model_name='clothing',
            name='design',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='fit',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='material',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='sizes_available',
            field=models.CharField(default='N/A', max_length=200),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='versatility',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
