# Generated by Django 5.1.6 on 2025-05-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0011_clothingtype_clothing_clothing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='address',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='payment',
            name='full_name',
            field=models.CharField(default='-', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(default='-', max_length=20),
        ),
    ]
