# Generated by Django 5.1.6 on 2025-05-15 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0012_payment_address_payment_full_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='return_item_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='return_proof',
            field=models.ImageField(blank=True, null=True, upload_to='return_proofs/'),
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('paid', 'ชำระเงินเรียบร้อยแล้ว'), ('packing', 'จัดเตรียมสินค้าแล้ว'), ('shipping', 'ดำเนินการจัดส่งแล้ว'), ('shipped', 'จัดส่งสำเร็จแล้ว'), ('returned', 'ได้รับคืนสินค้าเรียบร้อยแล้ว')], max_length=50)),
                ('tracking_number', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='clothing.payment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
