# Generated by Django 5.1.6 on 2025-05-26 17:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0014_payment_payment_ref_payment_qr_base64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_ref',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
